In [1]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.

import numpy as np
import pandas as pd

# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [ ]:
# function to create arrya with 10 zeros
def create_zeros_array():
	arr = np.zeros(10) # creating an numpy array of 10 elements, all initialized to 0
	arr[4] = 1 # set the fifth element (index 4) to 1
	return arr # returning the modified array

my_array = create_zeros_array() #calling the functions and store the returned array
print(my_array) # print the resulting array [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [ ]:
# solution
def create_matrix():
	arr_matrix = np.arange(16).reshape(4,4) # Creating a 4x4 matrix with values 0 to 15
	return arr_matrix # returning the matrix

matrix_arr = create_matrix() # calling function and storing the returned matrix
print(matrix_arr) # Printing the resulting matrix

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [ ]:
# solution
# Defining two matrices
arr1 = np.array(
	[
		[41,30,10],
		[6,35,23],
		[23,9,10]
	]
)

arr2 = np.array(
	[
		[4,29,2],
		[5,13,3],
		[24,16,7]
	]
)

# creating function that takes two arrays and do summation, subtraction, mulitiply and divide
def array_operatoins(a, b):

	# addition: arr1 + arr2
	arr_add = arr1 + arr2
	# subtraction: arr1 - arr2
	arr_sub = arr1 - arr2
	# division: arr1 / arr2
	arr_div = arr1 / arr2
	# multiplication: arr1 * arr2
	arr_mul = arr1 * arr2

	#printing results
	print(f"Matrix addition:: \n {arr_add} \n =============== \n")
	print(f"Matrix subtractoin:: \n {arr_sub} \n =============== \n")
	print(f"Matrix multiplication:: \n {arr_mul} \n =============== \n")
	print(f"Matrix divison:: \n {arr_div} \n =============== \n")

array_operatoins(arr1, arr2)  # calling the function

Matrix addition:: 
 [[45 59 12]
 [11 48 26]
 [47 25 17]] 

Matrix subtractoin:: 
 [[37  1  8]
 [ 1 22 20]
 [-1 -7  3]] 

Matrix multiplication:: 
 [[164 870  20]
 [ 30 455  69]
 [552 144  70]] 

Matrix divison:: 
 [[10.25        1.03448276  5.        ]
 [ 1.2         2.69230769  7.66666667]
 [ 0.95833333  0.5625      1.42857143]] 



### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [23]:
# Function to perform array slicing
def array_slicing():
    arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])  # Creating a NumPy array
    arr_elements = arr[2:7]  # Slicing elements from index 2 to 6 (7 is excluded)
    return arr_elements  # Returning the sliced elements

# Calling the function and storing the result
slice_elements = array_slicing()

# Printing the sliced elements
print(slice_elements)

[30 40 50 60 70]


### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [24]:
# define an array
arr = np.array(
	[
		[15,18,20],
		[15,30,8],
		[25,30,60]
	]
	)

# Function to perform aggregate matrix operations and NB: round the mean to two decimal places
def aggreate_matrix_operations(a):
    print(f"Input Array:\n{a}\n=================")  # Print the input array
    print(f"Mean of Array Elements: {round(a.mean(), 2)}")  # Mean rounded to two decimal places
    print(f"Sum of Array Elements: {round(a.sum(), 2)}")  # Sum of all elements in the array
    print(f"Maximum Value of Array: {round(a.max(), 2)}")  # Maximum value in the array

# Calling the function with the defined array
aggreate_matrix_operations(arr)

Input Array:
[[15 18 20]
 [15 30  8]
 [25 30 60]]
Mean of Array Elements: 24.56
Sum of Array Elements: 221
Maximum Value of Array: 60


# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [7]:
# solution
def create_pandas_series():

	data_list = [10,20,30,40,50]
	index_label = ['a','b','c','d','e']

	series = pd.Series(data_list, index_label)
	return series

pd_series = create_pandas_series()
print(pd_series)


a    10
b    20
c    30
d    40
e    50
dtype: int64


### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [8]:
# solution
def read_csv_file():
	df = pd.read_csv("data/data.csv")
	return df

df1 = read_csv_file()
print(df1.columns)

print(df1)

df = df1.rename(columns={"Salary": "Score"}, inplace = False)
df.columns


Index(['Name', 'Age', 'Salary'], dtype='object')
       Name  Age  Salary
0     Alice   29   73193
1       Bob   53   85398
2   Charlie   36   47162
3     David   22   65853
4       Eve   24   36168
5     Frank   58   69657
6     Grace   41   85202
7    Hannah   38   62421
8     Isaac   50   74641
9      Jack   47   38963
10    Karen   34   32136
11      Leo   49   41874
12     Mona   56   34070
13     Nina   49   91734
14    Oscar   30   89539
15     Paul   23   78720
16    Quinn   31   54424
17   Rachel   54   59900
18    Steve   36   32163
19     Tina   56   52054


Index(['Name', 'Age', 'Score'], dtype='object')

### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [9]:
def select_three_rows(df):
	return df.iloc[:3]

df_three_rows = select_three_rows(df1)
print(df_three_rows)


      Name  Age  Salary
0    Alice   29   73193
1      Bob   53   85398
2  Charlie   36   47162


### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [10]:
# solution
def add_column_tax(df, col_name):
	df[col_name] = round((df["Salary"] * 0.1), 2)
	return df

df_new = add_column_tax(df1,"Tax")
print(df_new)

       Name  Age  Salary     Tax
0     Alice   29   73193  7319.3
1       Bob   53   85398  8539.8
2   Charlie   36   47162  4716.2
3     David   22   65853  6585.3
4       Eve   24   36168  3616.8
5     Frank   58   69657  6965.7
6     Grace   41   85202  8520.2
7    Hannah   38   62421  6242.1
8     Isaac   50   74641  7464.1
9      Jack   47   38963  3896.3
10    Karen   34   32136  3213.6
11      Leo   49   41874  4187.4
12     Mona   56   34070  3407.0
13     Nina   49   91734  9173.4
14    Oscar   30   89539  8953.9
15     Paul   23   78720  7872.0
16    Quinn   31   54424  5442.4
17   Rachel   54   59900  5990.0
18    Steve   36   32163  3216.3
19     Tina   56   52054  5205.4


#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [11]:
# solution
def filter_age_condition(df):
	return df[df["Age"] > 36]

df_filtered = filter_age_condition(df1)
print(df_filtered)

      Name  Age  Salary     Tax
1      Bob   53   85398  8539.8
5    Frank   58   69657  6965.7
6    Grace   41   85202  8520.2
7   Hannah   38   62421  6242.1
8    Isaac   50   74641  7464.1
9     Jack   47   38963  3896.3
11     Leo   49   41874  4187.4
12    Mona   56   34070  3407.0
13    Nina   49   91734  9173.4
17  Rachel   54   59900  5990.0
19    Tina   56   52054  5205.4


# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [12]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()

Region  Sales
0  North   1000
1  South   1500
2  North   1200
3   West   1800
4  South   1300

In [13]:
# solution
# we use groupby() pandas function to compute the total and mean sales per region

# computing total and mean sales as per the region
sales_summary = sales_data.groupby("Region")["Sales"].agg(["sum", "mean"])

sales_summary.columns = ["Total Regional Sales", "Average sales"]
print(sales_summary)


        Total Regional Sales  Average sales
Region                                     
North                   2200         1100.0
South                   2800         1400.0
West                    3500         1750.0


### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [ ]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

print(customers.head(2) , "\n\n", orders.head(2))

   CustomerID CustomerName
0           1        Alice
1           2          Bob 

    OrderID  CustomerID  Amount
0      101           1     250
1      102           2     400


In [15]:
# solution
# Merging the customers and orderds dataframe wrt CustomerID to make customer_orders dataframe
customer_orders = pd.merge(customers, orders, on = "CustomerID")
print(customer_orders)

   CustomerID CustomerName  OrderID  Amount
0           1        Alice      101     250
1           2          Bob      102     400
2           2          Bob      103     600
3           4        David      104     150


### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [16]:
# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

print(employees.head(2), "\n\n", departments.head(2))

   EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2 

    DeptID DeptName
0       1       HR
1       2  Finance


In [17]:
print(employees, "\n\n" , departments)

   EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2
2    103   Alice       2
3    104     Bob       3 

    DeptID DeptName
0       1       HR
1       2  Finance


In [18]:
# solution
left_join = employees.merge(departments, on="DeptID", how="left")
print(left_join)

   EmpID EmpName  DeptID DeptName
0    101    John       1       HR
1    102    Jane       2  Finance
2    103   Alice       2  Finance
3    104     Bob       3      NaN


### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [19]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

Region Product  Sales
0  North       A    200
1  North       B    300

In [20]:
sales_pivot_data

Region Product  Sales
0  North       A    200
1  North       B    300
2  South       A    150
3  South       B    400
4   West       A    250
5   West       B    500

In [21]:
# solution
# A pivot table is a means to organize summarize data dynamically by rearranging rows and columns. Help in  grouping, aggregating, and analyzing large datasets.

# Pivoting to show sales group by Region and product
sales_pivot = sales_pivot_data.pivot_table(index="Region", columns="Product", values="Sales")
print(sales_pivot)


Product      A      B
Region               
North    200.0  300.0
South    150.0  400.0
West     250.0  500.0
